import java.util.*;

class CustomException
{
	public static void main(String[] args)
	{
		try
		{
			Scanner sc=new Scanner(System.in);

			System.out.print("Enter the number : ");
			int num=sc.nextInt();

			System.out.println("No Exception occurs");
			
			System.out.println("Number is :"+num);
		}

		catch(InputMismatchException e)
		{
			System.out.println("Exception occurs "+e);		
		
		}
	}
}
